<section class="v2-page-heading"><div><p class="v2-eyebrow">MONBIS WORKSPACE</p><h1>FE Component Library</h1><p>Komponen dasar untuk membangun semua halaman MONBIS dengan pengalaman yang konsisten.</p></div><div class="v2-page-status"><?= v2_badge('●  API online', 'success') ?></div></section>
<section class="v2-library-hero"><div><p class="v2-eyebrow">DESIGN SYSTEM</p><h2>Bangun sekali, pakai di semua page.</h2><p>Semua halaman baru cukup merakit component yang sama. Warna, spacing, state, dan perilaku responsive terpusat di FE.</p></div><div class="v2-library-mark">UI<small>v0.1</small></div></section>
<section class="v2-showcase-section"><div class="v2-section-heading"><div><p class="v2-eyebrow">FEEDBACK</p><h2>Alert &amp; notification</h2></div><span class="v2-section-code">v2_alert · v2_toast</span></div><div class="v2-form-stack"><?= v2_alert('Data pegawai berhasil disimpan.', 'success', 'Berhasil') ?><?= v2_alert('Lengkapi field wajib sebelum melanjutkan.', 'warning', 'Perhatian') ?></div></section>
<section class="v2-showcase-section"><div class="v2-section-heading"><div><p class="v2-eyebrow">ELEMENTS</p><h2>Reusable components</h2></div><div class="v2-actions"><?= v2_button('Tampilkan toast', 'primary', 'check', ['data-v2-toast'=>'Komponen toast siap dipakai.']) ?></div></div><div class="v2-component-grid">
  <?= v2_card_open('Tabs dan badge', 'Navigasi konteks tanpa membuat page penuh.') ?><div class="v2-card-body"><?= v2_tabs(['overview'=>'Overview', 'detail'=>'Detail', 'history'=>'History'], 'overview') ?><div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:14px"><?= v2_badge('Active', 'success') ?><?= v2_badge('Draft', 'warning') ?><?= v2_badge('Approved') ?></div></div><?= v2_card_close() ?>
  <?= v2_card_open('Progress dan table', 'Status dan data memakai token yang sama.') ?><div class="v2-card-body v2-form-stack"><?= v2_progress(68, 'Migrasi page') ?><div class="v2-table-wrap"><table class="v2-table"><thead><tr><th>Komponen</th><th>Status</th></tr></thead><tbody><tr><td>Responsive table</td><td><?= v2_badge('Ready', 'success') ?></td></tr><tr><td>Modal overlay</td><td><?= v2_badge('Ready', 'success') ?></td></tr></tbody></table></div></div><?= v2_card_close() ?>
  <?= v2_card_open('Form dan modal', 'Helper PHP dan data attribute JS tersedia.') ?><div class="v2-card-body"><div class="v2-filter-bar" style="margin:0"><?= v2_input('demoSearch', 'Pencarian', '', 'Cari komponen...') ?><?= v2_select('demoStatus', 'Status', ['all'=>'Semua', 'ready'=>'Ready'], 'all') ?><?= v2_button('Buka modal', 'secondary', 'file', ['data-v2-modal-open'=>'v2KitModal']) ?></div></div><?= v2_card_close() ?>
</div></section>
<section class="v2-showcase-section"><div class="v2-section-heading"><div><p class="v2-eyebrow">STATES</p><h2>Loading, empty &amp; pagination</h2></div><span class="v2-section-code">v2_spinner · v2_skeleton · v2_empty_state</span></div><div class="v2-component-grid">
  <?= v2_card_open('Loading state', 'Untuk proses API, export, dan submit.') ?><div class="v2-card-body v2-form-stack"><?= v2_spinner('Mengambil data...') ?><?= v2_skeleton('title') ?><?= v2_skeleton('card') ?></div><?= v2_card_close() ?>
  <?= v2_card_open('Empty state', 'Jangan biarkan ruang kosong tanpa konteks.') ?><div class="v2-card-body"><?= v2_empty_state('Belum ada laporan', 'Pilih periode dan cabang untuk menampilkan data.', 'file') ?></div><?= v2_card_close() ?>
  <?= v2_card_open('Switch dan pagination', 'Control kecil tetap memakai pola visual yang sama.') ?><div class="v2-card-body v2-form-stack"><?= v2_switch('demoSwitch', 'Aktifkan notifikasi', true) ?><?= v2_pagination(2, 4) ?></div><?= v2_card_close() ?>
</div></section>
<?= v2_modal('v2KitModal', 'Modal component', '<p class="v2-empty">Modal ini memakai helper <span class="v2-code-chip">v2_modal()</span> dan dapat dipanggil dari page mana pun.</p>') ?>
