<?php
$tab = strtolower((string)($_GET['tab'] ?? 'projection'));
if (!in_array($tab, ['projection', 'detail', 'aba'], true)) $tab = 'projection';
$rbbCategory = strtoupper((string)($_GET['category'] ?? 'ASET'));
if (!in_array($rbbCategory, ['ASET','KREDIT','DAMAS','PENDAPATAN','BEBAN','LIABILITAS','EKUITAS','IKHTISAR','ALL'], true)) $rbbCategory = 'ASET';
$tabUrl = static fn(string $name): string => $baseUrl . '/rbb/?tab=' . rawurlencode($name);
$bankReferences = [
    'PT BANK DANAMON INDONESIA, Tbk', 'PT BANK MANDIRI (PERSERO), Tbk', 'PT BANK MASPION INDONESIA',
    'PT BANK MAYAPADA INTERNASIONAL, Tbk', 'PT BANK MEGA SYARIAH', 'PT BANK MUAMALAT INDONESIA',
    'PT BANK NEGARA INDONESIA (PERSERO), Tbk', 'PT BANK PEMBANGUNAN DAERAH BANTEN, Tbk',
    'PT BANK PERMATA, Tbk', 'PT BANK RAKYAT INDONESIA (PERSERO), Tbk', 'PT BANK SMC INDONESIA, Tbk',
    'PT BPD JAWA TENGAH', 'PT BPR ARTHA KARYA USAHA', 'PT BPR BKK TEMANGGUNG', 'PT BPR KOTA SEMARANG',
    'PT BPR DANAMAS ADI PERKASA', 'PT BPR HALIM PRIMA', 'PT BPR KARYA PRIMA SENTOSA', 'PT BPR LAWU ARTHA',
    'PT BPR LINGGA SEJAHTERA', 'PT BPR LUNA SINAR INDONESIA', 'PT BPR PARASAHAT BEKASI', 'PT BPR TATA ASIA',
    'PT BPRS KEDUNG ARTO', 'PT BPRS PNM MENTARI', 'Bank Umum Lainnya', 'BPR Lainnya',
];
?>
<section class="v2-page-heading v2-module-heading">
  <div><p class="v2-eyebrow">MONBIS / INPUT RBB</p><h1>Input RBB</h1><p>Proyeksi, input detail COA, dan ABA dibangun ulang dengan component FE V2.</p></div>
  <div class="v2-page-status"><?= v2_badge('Akses terbatas', 'warning') ?></div>
</section>

<?= v2_filter_drawer([
    ['name'=>'year', 'id'=>'v2RbbYear', 'label'=>'Tahun RBB', 'type'=>'number', 'value'=>'2027', 'attrs'=>['min'=>'2020','max'=>'2100','step'=>'1']],
    ['name'=>'branch', 'id'=>'v2RbbBranch', 'label'=>'Kantor / Cabang', 'type'=>'select', 'value'=>'', 'options'=>[''=>'Memuat kantor...']],
    ['name'=>'category', 'id'=>'v2RbbCategory', 'label'=>'Kategori COA', 'type'=>'select', 'value'=>$rbbCategory, 'options'=>['ASET'=>'Aset','KREDIT'=>'Kredit','DAMAS'=>'DAMAS','PENDAPATAN'=>'Pendapatan','BEBAN'=>'Beban','LIABILITAS'=>'Liabilitas','EKUITAS'=>'Ekuitas','IKHTISAR'=>'Ikhtisar','ALL'=>'Semua kategori']],
], 'v2RbbFilters') ?>

<datalist id="v2RbbBankReference"><?php foreach ($bankReferences as $bank): ?><option value="<?= v2_e($bank) ?>"><?php endforeach; ?></datalist>
<section class="v2-card v2-module-shell">
  <div class="v2-card-heading v2-module-toolbar">
    <div><h2><?= $tab === 'projection' ? 'Proyeksi RBB' : ($tab === 'detail' ? 'Input Detail RBB' : 'Input RBB ABA') ?></h2><p>Data disimpan ke API RBB yang sama dengan V1 sampai FE baru dinyatakan siap menggantikan.</p></div>
    <nav class="v2-tabs v2-module-tabs" aria-label="Menu Input RBB">
      <a class="v2-tab<?= $tab === 'projection' ? ' is-active' : '' ?>" href="<?= v2_e($tabUrl('projection')) ?>">Proyeksi</a>
      <a class="v2-tab<?= $tab === 'detail' ? ' is-active' : '' ?>" href="<?= v2_e($tabUrl('detail')) ?>">Input Detail</a>
      <a class="v2-tab<?= $tab === 'aba' ? ' is-active' : '' ?>" href="<?= v2_e($tabUrl('aba')) ?>">ABA</a>
    </nav>
  </div>
  <div class="v2-card-body v2-module-body">
<?php if ($tab === 'projection'): ?>
    <div class="v2-module-callout"><div><strong>Proyeksi <?= v2_e('RBB') ?></strong><p>Nilai dari ABA otomatis masuk ke COA 104, CKPN, dan pendapatan bunga.</p></div><span class="v2-module-status" id="v2RbbProjectionStatus">-</span><div class="v2-actions v2-rbb-approval-actions"><button type="button" class="v2-button v2-button--primary" id="v2RbbSubmit" hidden>Ajukan</button><button type="button" class="v2-button v2-button--success" id="v2RbbApproveKanwil" hidden>Approve Kanwil</button><button type="button" class="v2-button v2-button--success" id="v2RbbApprovePusat" hidden>Approve Pusat</button><button type="button" class="v2-button v2-button--danger" id="v2RbbReject" hidden>Tolak</button></div></div>
    <div class="v2-table-wrap v2-module-table-wrap"><table class="v2-table v2-rbb-projection-table"><thead><tr><th>KODE</th><th>COA / INDIKATOR</th><th>KATEGORI</th><th>SUMBER</th><?php foreach (['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'] as $month): ?><th><?= $month ?></th><?php endforeach; ?><th>TOTAL</th></tr></thead><tbody id="v2RbbProjectionBody"><tr><td colspan="17" class="v2-empty">Memuat proyeksi RBB...</td></tr></tbody></table></div>
<?php elseif ($tab === 'detail'): ?>
    <div class="v2-module-callout"><div><strong>Input manual detail RBB</strong><p>Baris AUTO dikunci dan mengikuti formula backend. Baris MANUAL dapat diisi per bulan.</p></div><button type="button" class="v2-button v2-button--primary" id="v2RbbDetailSave"><?= v2_icon('check', 16) ?><span>Simpan draft</span></button></div>
    <div class="v2-module-progress" id="v2RbbDetailStatus">Draft belum dimuat.</div>
    <div class="v2-table-wrap v2-module-table-wrap"><table class="v2-table v2-rbb-detail-table"><thead><tr><th>KODE</th><th>COA / INDIKATOR</th><th>INPUT</th><?php foreach (['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'] as $month): ?><th><?= $month ?></th><?php endforeach; ?><th>TOTAL</th></tr></thead><tbody id="v2RbbDetailBody"><tr><td colspan="16" class="v2-empty">Memuat detail RBB...</td></tr></tbody></table></div>
<?php else: ?>
    <div class="v2-module-callout"><div><strong>Penempatan pada bank lain</strong><p>CKPN otomatis 0,5% dari nominal ABA dan pendapatan bunga memakai formula nominal × (1,25% / 12).</p></div><div class="v2-actions"><button type="button" class="v2-button v2-button--primary" id="v2RbbAbaAdd"><?= v2_icon('plus', 16) ?><span>Tambah baris</span></button><button type="button" class="v2-button v2-button--success" id="v2RbbAbaSave"><?= v2_icon('check', 16) ?><span>Simpan</span></button></div></div>
    <div class="v2-tabs v2-aba-tabs" role="tablist" aria-label="Bagian ABA"><button class="v2-tab is-active" type="button" data-v2-aba-view="placement">COA ABA</button><button class="v2-tab" type="button" data-v2-aba-view="ckpn">CKPN ABA</button><button class="v2-tab" type="button" data-v2-aba-view="interest">Pendapatan Bank Lain</button><button class="v2-tab" type="button" data-v2-aba-view="history">History 3 Tahun</button></div>
    <div class="v2-module-progress" id="v2RbbAbaStatus">Memuat ABA...</div>
    <div class="v2-table-wrap v2-module-table-wrap"><table class="v2-table v2-rbb-aba-table"><thead id="v2RbbAbaHead"></thead><tbody id="v2RbbAbaBody"><tr><td colspan="19" class="v2-empty">Memuat ABA...</td></tr></tbody></table></div>
<?php endif; ?>
  </div>
</section>

<script>
(() => {
  const TAB = <?= json_encode($tab) ?>;
  const API = <?= json_encode($legacyBase . '/api/rbb/') ?>;
  const API_KODE = <?= json_encode($legacyBase . '/api/kode/') ?>;
  const months = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];
  const state = { rows: [], plan: null, offices: [], abaView: 'placement', history: null, interestRate: .0125 };
  const el = (id) => document.getElementById(id);
  const field = (name) => document.querySelector(`[data-v2-filter-field="${name}"]`);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const num = (value) => Number(value || 0);
  const fmt = (value) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 }).format(num(value));
  const post = async (body) => { const response = await fetch(API, {method:'POST', credentials:'same-origin', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)}); const json = await response.json().catch(() => ({})); if (!response.ok || Number(json.status) !== 200) throw new Error(json.message || `Request RBB gagal (${response.status})`); return json.data || {}; };
  const toast = (message) => window.V2Toast?.show(message) || window.alert(message);
  const filters = () => ({ tahun:field('year')?.value || 2027, kode_kantor:field('branch')?.value || '', kategori:field('category')?.value || 'ASET' });
  const showError = (id, message, colspan) => { const node = el(id); if (node) node.innerHTML = `<tr><td colspan="${colspan}" class="v2-empty v2-negative">${esc(message)}</td></tr>`; };
  function fillOffices(rows) { state.offices = rows || []; const select = el('v2RbbBranch'); if (!select) return; const current = select.value; select.innerHTML = rows.length ? rows.map(item => `<option value="${esc(String(item.kode_kantor).padStart(3,'0'))}">${esc(String(item.kode_kantor).padStart(3,'0'))} · ${esc(item.nama_kantor || 'Cabang')}</option>`).join('') : '<option value="">Kantor tidak tersedia</option>'; if (rows.some(item => String(item.kode_kantor).padStart(3,'0') === current)) select.value = current; else if (rows[0]) select.value = String(rows[0].kode_kantor).padStart(3,'0'); }
  function money(value) { return fmt(value); }
  function renderProjection(data) { state.rows = data.rows || []; state.plan = data.plan || null; el('v2RbbProjectionStatus').textContent = state.plan?.status || 'Draft baru'; updateProjectionActions(); const body = el('v2RbbProjectionBody'); body.innerHTML = state.rows.length ? state.rows.map(row => `<tr><td class="v2-code">${esc(row.kode_monbis)}</td><td><strong>${esc(row.keterangan || '-')}</strong><small>${esc(row.kode_perkiraan || '-')}</small></td><td>${esc(row.kategori || '-')}</td><td>${v2Badge(row.source || 'INPUT COA', row.source === 'INPUT ABA' ? 'success' : 'default')}</td>${months.map((_, i) => `<td class="v2-num">${money(row.values?.[i + 1])}</td>`).join('')}<td class="v2-num"><strong>${money(row.total)}</strong></td></tr>`).join('') : '<tr><td colspan="17" class="v2-empty">Belum ada COA proyeksi.</td></tr>'; }
  function updateProjectionActions() { const status = state.plan?.status || ''; const actions = {submit:['DRAFT','REJECTED'].includes(status), approveKanwil:status === 'SUBMITTED_KANWIL', approvePusat:status === 'APPROVED_KANWIL', reject:['SUBMITTED_KANWIL','APPROVED_KANWIL'].includes(status)}; el('v2RbbSubmit')?.toggleAttribute('hidden', !actions.submit); el('v2RbbApproveKanwil')?.toggleAttribute('hidden', !actions.approveKanwil); el('v2RbbApprovePusat')?.toggleAttribute('hidden', !actions.approvePusat); el('v2RbbReject')?.toggleAttribute('hidden', !actions.reject); }
  function v2Badge(label, tone) { const palette = tone === 'success' ? 'v2-inline-badge v2-inline-badge--success' : 'v2-inline-badge'; return `<span class="${palette}">${esc(label)}</span>`; }
  function renderDetail(data) { state.rows = data.rows || []; state.plan = data.plan || null; const editable = data.permissions?.can_edit !== false; const status = state.plan?.status || 'DRAFT'; el('v2RbbDetailStatus').textContent = `Status ${status} · ${editable ? 'dapat diedit' : 'terkunci'}`; const sums = Array(13).fill(0); state.rows.forEach(row => months.forEach((_, i) => sums[i + 1] += num(row.values?.[i + 1]))); const total = `<tr class="v2-total-row"><td>-</td><td><strong>GRAND TOTAL</strong></td><td>-</td>${months.map((_, i) => `<td class="v2-num"><strong>${money(sums[i + 1])}</strong></td>`).join('')}<td class="v2-num"><strong>${money(sums.slice(1).reduce((a,b) => a + b, 0))}</strong></td></tr>`; const rows = state.rows.map(row => { const auto = row.input_mode === 'AUTO'; return `<tr data-rbb-code="${esc(row.kode_monbis)}"><td class="v2-code">${esc(row.kode_monbis)}</td><td><strong>${esc(row.keterangan || '-')}</strong><small>${esc(row.kode_perkiraan || '-')}</small></td><td>${v2Badge(auto ? 'AUTO' : 'MANUAL', auto ? 'default' : 'success')}</td>${months.map((_, i) => `<td><input class="v2-inline-input v2-rbb-number" data-rbb-month="${i + 1}" value="${num(row.values?.[i + 1])}" inputmode="decimal" type="number" min="0" step="0.01"${auto || !editable ? ' disabled' : ''}></td>`).join('')}<td class="v2-num v2-rbb-row-total">${money(row.total)}</td></tr>`; }).join(''); el('v2RbbDetailBody').innerHTML = state.rows.length ? total + rows : '<tr><td colspan="16" class="v2-empty">Belum ada COA pada kategori ini.</td></tr>'; }
  function renderAbaHead(view) { const base = '<tr><th>AKSI</th><th>NO</th><th>JENIS</th><th>NAMA BANK</th><th>NO. ABA</th><th>NO. CBS</th>'; if (view === 'history') { const years = state.history?.years || [2024, 2025, 2026]; el('v2RbbAbaHead').innerHTML = `<tr><th rowspan="2">BULAN</th><th colspan="3">PENEMPATAN ABA</th><th colspan="3">CKPN ABA</th><th colspan="3">PENDAPATAN BUNGA</th></tr><tr>${years.map(year => `<th>${year}</th>`).join('')}${years.map(year => `<th>${year}</th>`).join('')}${years.map(year => `<th>${year}</th>`).join('')}</tr>`; return; } el('v2RbbAbaHead').innerHTML = base + months.map(month => `<th>${month}</th>`).join('') + '<th>TOTAL</th></tr>'; }
  function renderAba() { const view = state.abaView; renderAbaHead(view); const body = el('v2RbbAbaBody'); const rows = state.rows; if (view === 'history') { const history = state.history || {}, years = history.years || [2024, 2025, 2026]; body.innerHTML = months.map((month, i) => `<tr><td>${month}</td>${years.map(year => `<td class="v2-num">${money(history.nominal?.[year]?.[i + 1])}</td>`).join('')}${years.map(year => `<td class="v2-num">${money(history.ckpn?.[year]?.[i + 1])}</td>`).join('')}${years.map(year => `<td class="v2-num">${money(history.interest?.[year]?.[i + 1])}</td>`).join('')}</tr>`).join(''); return; } if (!rows.length) { body.innerHTML = '<tr><td colspan="19" class="v2-empty">Belum ada rekening. Klik Tambah baris untuk mulai mengisi.</td></tr>'; return; } const factor = view === 'ckpn' ? .005 : state.interestRate / 12; body.innerHTML = rows.map((row, index) => { const values = row.values || {}, interest = row.interest_values || {}; const readonly = view !== 'placement'; const cells = months.map((_, i) => { const value = view === 'ckpn' ? num(values[i + 1]) * factor : view === 'interest' ? num(interest[i + 1]) : num(values[i + 1]); return readonly ? `<td class="v2-num">${money(value)}</td>` : `<td><input class="v2-inline-input v2-rbb-number" data-aba-month="${i + 1}" value="${num(value)}" inputmode="decimal" type="number" min="0" step="0.01"></td>`; }).join(''); const total = months.reduce((sum, _, i) => sum + (view === 'ckpn' ? num(values[i + 1]) * factor : view === 'interest' ? num(interest[i + 1]) : num(values[i + 1])), 0); return `<tr data-aba-index="${index}"><td>${readonly ? '-' : `<button type="button" class="v2-delete-button" data-aba-delete="${index}" aria-label="Hapus baris">×</button>`}</td><td>${index + 1}</td><td><select class="v2-inline-input" data-aba-field="jenis"${readonly ? ' disabled' : ''}><option value="Tabungan"${row.jenis_penempatan === 'Tabungan' ? ' selected' : ''}>Tabungan</option><option value="Deposito"${row.jenis_penempatan === 'Deposito' ? ' selected' : ''}>Deposito</option><option value="Giro"${row.jenis_penempatan === 'Giro' ? ' selected' : ''}>Giro</option></select></td><td><input class="v2-inline-input v2-aba-bank" list="v2RbbBankReference" data-aba-field="bank" value="${esc(row.nama_bank || '')}"${readonly ? ' disabled' : ''}></td><td><input class="v2-inline-input" data-aba-field="aba" value="${esc(row.no_rekening_aba || '')}"${readonly ? ' disabled' : ''}></td><td><input class="v2-inline-input" data-aba-field="cbs" value="${esc(row.no_rekening_cbs || '')}"${readonly ? ' disabled' : ''}></td>${cells}<td class="v2-num"><strong>${money(total)}</strong></td></tr>`; }).join(''); }
  function collectDetail() { return state.rows.map(row => { const tr = document.querySelector(`[data-rbb-code="${CSS.escape(row.kode_monbis)}"]`); return {kode_monbis:row.kode_monbis, values:Object.fromEntries([...tr.querySelectorAll('[data-rbb-month]')].map(input => [input.dataset.rbbMonth, num(input.value)]))}; }); }
  function collectAba() { return [...document.querySelectorAll('#v2RbbAbaBody tr[data-aba-index]')].map((tr, index) => ({id:num(state.rows[index]?.id), no_urut:index + 1, jenis_penempatan:tr.querySelector('[data-aba-field="jenis"]')?.value || 'Tabungan', nama_bank:tr.querySelector('[data-aba-field="bank"]')?.value || '', no_rekening_aba:tr.querySelector('[data-aba-field="aba"]')?.value || '', no_rekening_cbs:tr.querySelector('[data-aba-field="cbs"]')?.value || '', values:Object.fromEntries([...tr.querySelectorAll('[data-aba-month]')].map(input => [input.dataset.abaMonth, num(input.value)]))})); }
  async function load() { try { const data = TAB === 'projection' ? await post({type:'rbb_projection_data', ...filters()}) : TAB === 'detail' ? await post({type:'rbb_planning_data', ...filters()}) : await post({type:'rbb_aba_data', tahun:field('year').value, kode_kantor:field('branch').value, tipe:'PLACEMENT'}); if (TAB === 'projection') renderProjection(data); else if (TAB === 'detail') renderDetail(data); else { state.rows = data.rows || []; state.plan = data.plan || null; state.history = data.history || null; state.interestRate = num(data.interest_rate) || .0125; el('v2RbbAbaStatus').textContent = `Status ${state.plan?.status || 'DRAFT'} · Rate bunga ${(state.interestRate * 100).toFixed(2)}% per tahun`; renderAba(); } } catch (error) { const target = TAB === 'projection' ? 'v2RbbProjectionBody' : TAB === 'detail' ? 'v2RbbDetailBody' : 'v2RbbAbaBody'; showError(target, error.message, TAB === 'aba' ? 19 : TAB === 'detail' ? 16 : 17); } }
  async function transition(action) { if (!state.plan) return toast('Belum ada draft RBB.'); const message = action === 'REJECT' ? 'Tolak draft RBB ini?' : action === 'SUBMIT_KANWIL' ? 'Ajukan draft RBB ke Kanwil?' : action === 'APPROVE_KANWIL' ? 'Approve draft RBB sebagai Kanwil?' : 'Approve draft RBB sebagai Pusat?'; if (!window.confirm(message)) return; try { const payload = action === 'SUBMIT_KANWIL' ? {type:'rbb_planning_submit', tahun:field('year').value, kode_kantor:field('branch').value} : {type:'rbb_planning_approve', action, tahun:field('year').value, kode_kantor:field('branch').value}; await post(payload); toast('Status Proyeksi RBB berhasil diperbarui.'); await load(); } catch (error) { toast(error.message); } }
  async function init() { try { const response = await fetch(API_KODE, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({type:'kode_kantor'})}); const json = await response.json(); fillOffices(Array.isArray(json.data) ? json.data.filter(item => String(item.kode_kantor) !== '000') : []); await load(); } catch (error) { const target = TAB === 'projection' ? 'v2RbbProjectionBody' : TAB === 'detail' ? 'v2RbbDetailBody' : 'v2RbbAbaBody'; showError(target, error.message, TAB === 'aba' ? 19 : TAB === 'detail' ? 16 : 17); } }
  ['year','branch','category'].forEach(name => field(name)?.addEventListener('change', load));
  el('v2RbbDetailSave')?.addEventListener('click', async () => { const button = el('v2RbbDetailSave'); button.disabled = true; try { await post({type:'rbb_planning_save', tahun:field('year').value, kode_kantor:field('branch').value, kategori:field('category').value, rows:collectDetail()}); toast('Draft RBB berhasil disimpan.'); await load(); } catch (error) { toast(error.message); } finally { button.disabled = false; } });
  el('v2RbbAbaAdd')?.addEventListener('click', () => { state.rows.push({id:0, jenis_penempatan:'Tabungan', nama_bank:'', no_rekening_aba:'', no_rekening_cbs:'', values:Object.fromEntries(months.map((_, i) => [i + 1, 0])), interest_values:Object.fromEntries(months.map((_, i) => [i + 1, 0]))}); renderAba(); });
  el('v2RbbAbaSave')?.addEventListener('click', async () => { const button = el('v2RbbAbaSave'); button.disabled = true; try { await post({type:'rbb_aba_save', tahun:field('year').value, kode_kantor:field('branch').value, rows:collectAba()}); toast('Input ABA berhasil disimpan.'); await load(); } catch (error) { toast(error.message); } finally { button.disabled = false; } });
  el('v2RbbSubmit')?.addEventListener('click', () => transition('SUBMIT_KANWIL'));
  el('v2RbbApproveKanwil')?.addEventListener('click', () => transition('APPROVE_KANWIL'));
  el('v2RbbApprovePusat')?.addEventListener('click', () => transition('APPROVE_PUSAT'));
  el('v2RbbReject')?.addEventListener('click', () => transition('REJECT'));
  document.addEventListener('click', (event) => { const deleteButton = event.target.closest('[data-aba-delete]'); if (deleteButton) { state.rows.splice(Number(deleteButton.dataset.abaDelete), 1); renderAba(); } const viewButton = event.target.closest('[data-v2-aba-view]'); if (viewButton) { state.abaView = viewButton.dataset.v2AbaView; document.querySelectorAll('[data-v2-aba-view]').forEach(item => item.classList.toggle('is-active', item === viewButton)); el('v2RbbAbaAdd')?.toggleAttribute('hidden', state.abaView !== 'placement'); el('v2RbbAbaSave')?.toggleAttribute('hidden', state.abaView !== 'placement'); renderAba(); } });
  init();
})();
</script>
