<?php
require_once __DIR__ . '/../components/bootstrap.php';
mb_ui_assets('.');
$part = strtolower((string)($_GET['bagian'] ?? 'kredit'));
$map = ['kredit'=>['KREDIT','Kredit'], 'damas'=>['DAMAS','DAMAS'], 'pendapatan'=>['PENDAPATAN','Pendapatan'], 'beban'=>['BEBAN','Beban']];
[$category, $label] = $map[$part] ?? $map['kredit'];
$tabs = '<div class="mb-segmented">'.'<a class="mb-segmented__btn" href="input_rbb">'.mb_svg('chart').'<span class="mb-icon-button__label">Proyeksi</span></a><span class="mb-segmented__btn is-active">'.mb_svg('edit').'<span class="mb-icon-button__label">Input '.$label.'</span></span></div>';
mb_render_report_page([
  'id'=>'inputRbbDetailPage','class'=>'mb-report-rbb-detail',
  'header'=>['id'=>'inputRbbDetailHeader','title'=>'Input RBB '.$label,'subtitle'=>'Input detail bulanan yang menjadi sumber Proyeksi RBB.','icon'=>mb_svg('edit'),'info_modal_id'=>'inputRbbDetailInfo','filters'=>[
    ['id'=>'inputRbbDetailTahun','label'=>'Tahun RBB','type'=>'number','width'=>'115px','value'=>'2027','attrs'=>['min'=>'2020','max'=>'2100','step'=>'1']],
    ['id'=>'inputRbbDetailCabang','label'=>'Kantor / Cabang','type'=>'select','width'=>'230px','options'=>[''=>'Memuat kantor...']],
  ]],
  'toolbar'=>['title'=>'Input '.$label,'title_id'=>'inputRbbDetailTitle','leading_html'=>'<span id="inputRbbDetailStatus" class="mb-rbb-planning-status">Draft</span>','before_html'=>$tabs,'actions'=>[
    ['attrs'=>['id'=>'inputRbbDetailSave'],'tone'=>'success','icon'=>'save','label'=>'Simpan Draft','title'=>'Simpan draft','aria_label'=>'Simpan draft'],
  ]],
  'table'=>['wrapper_id'=>'inputRbbDetailTableWrap','table_id'=>'inputRbbDetailTable','loading_id'=>'inputRbbDetailLoading','loading_text'=>'Memuat COA...','class'=>'mb-rbb-detail-table','colgroup_html'=>'<col class="rbb-detail-code"><col class="rbb-detail-name"><col class="rbb-detail-mode"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-month"><col class="rbb-detail-total">','thead_html'=>'<tr><th>KODE</th><th>COA / INDIKATOR</th><th>INPUT</th><th>JAN</th><th>FEB</th><th>MAR</th><th>APR</th><th>MEI</th><th>JUN</th><th>JUL</th><th>AGU</th><th>SEP</th><th>OKT</th><th>NOV</th><th>DES</th><th>TOTAL</th></tr>','tbody_ids'=>['inputRbbDetailTotal','inputRbbDetailBody']]
]);
mb_render_info_modal(['id'=>'inputRbbDetailInfo','title'=>'Panduan Input '.$label,'subtitle'=>'Nilai manual akan tampil di Proyeksi RBB.','body_html'=>'<div class="mb-npl-brief"><div class="mb-npl-brief__alert"><strong>COA berstatus AUTO tidak dapat diisi langsung.</strong><span>Nilai tersebut dihitung dari detail atau formula terkait.</span></div></div>']);
?>
<style>
  #inputRbbDetailPage .mb-report-card{overflow:hidden} #inputRbbDetailPage .mb-rbb-planning-status{display:inline-flex;align-items:center;min-height:28px;padding:5px 9px;border:1px solid #dbe5f0;border-radius:8px;color:#64748b;background:#f8fafc;font-size:10px;font-weight:800;white-space:nowrap}
  #inputRbbDetailPage .mb-rbb-detail-table{min-width:1320px;table-layout:fixed} #inputRbbDetailPage .rbb-detail-code{width:70px} #inputRbbDetailPage .rbb-detail-name{width:300px} #inputRbbDetailPage .rbb-detail-mode{width:80px} #inputRbbDetailPage .rbb-detail-month{width:84px} #inputRbbDetailPage .rbb-detail-total{width:110px}
  #inputRbbDetailPage .rbb-detail-input{width:100%;min-width:0;padding:6px 5px;border:1px solid #d7e1ec;border-radius:5px;color:#17375f;text-align:right;font:700 10px ui-monospace,SFMono-Regular,Menlo,monospace} #inputRbbDetailPage .rbb-detail-input:disabled{background:#eef2f7;color:#94a3b8}
  @media(max-width:767px){#inputRbbDetailPage .mb-icon-button__label{display:none}#inputRbbDetailPage .rbb-detail-name{width:220px}#inputRbbDetailPage .rbb-detail-month{width:74px}}
</style>
<script>
(()=>{const API='./api/rbb/',API_KODE='./api/kode/',CATEGORY=<?=json_encode($category)?>,state={rows:[],plan:null,loading:false},el=id=>document.getElementById(id),ui=()=>window.MonbisUI||{},esc=v=>ui().escape?ui().escape(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),num=v=>Number(v||0),fmt=v=>ui().fmt?ui().fmt(Math.round(num(v))):new Intl.NumberFormat('id-ID').format(Math.round(num(v))),months=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];
  async function post(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),raw=await r.text();let j={};try{j=raw?JSON.parse(raw):{}}catch(e){throw new Error('Response API bukan JSON.')}if(!r.ok||Number(j.status)!==200)throw new Error(j.message||'Request gagal.');return j.data||{}}
  const year=()=>Number(el('inputRbbDetailTahun').value||2027),branch=()=>el('inputRbbDetailCabang').value;
  function render(){const body=el('inputRbbDetailBody'),total=el('inputRbbDetailTotal');if(!state.rows.length){total.innerHTML='';body.innerHTML='<tr><td colspan="16" class="mb-empty">Belum ada COA.</td></tr>';return}const edit=!state.plan||['DRAFT','REJECTED'].includes(state.plan.status),sums=Array(13).fill(0);state.rows.forEach(r=>{for(let m=1;m<=12;m++)sums[m]+=num(r.values?.[m])});total.innerHTML='<tr class="mb-total-row"><td>-</td><td>GRAND TOTAL</td><td>-</td>'+sums.slice(1).map(v=>'<td class="mb-num">'+fmt(v)+'</td>').join('')+'<td class="mb-num">'+fmt(sums.slice(1).reduce((a,b)=>a+b,0))+'</td></tr>';body.innerHTML=state.rows.map(r=>{const auto=r.input_mode==='AUTO',vals=r.values||{},sum=Object.values(vals).reduce((a,b)=>a+num(b),0);return '<tr><td class="font-mono text-blue-700">'+esc(r.kode_monbis)+'</td><td class="font-bold text-left">'+esc(r.keterangan||'-')+'</td><td><span class="rbb-plan-mode-badge rbb-plan-mode-badge--'+(auto?'auto':'manual')+'">'+(auto?'AUTO':'MANUAL')+'</span></td>'+months.map((_,i)=>'<td><input class="rbb-detail-input" type="number" min="0" step="0.01" data-code="'+esc(r.kode_monbis)+'" data-month="'+(i+1)+'" value="'+num(vals[i+1])+'"'+(auto||!edit?' disabled':'')+'></td>').join('')+'<td class="mb-num font-bold">'+fmt(sum)+'</td></tr>'}).join('')}
  async function offices(){const r=await fetch(API_KODE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'kode_kantor'})}),j=await r.json(),rows=Array.isArray(j.data)?j.data:(j.data?.data||[]);el('inputRbbDetailCabang').innerHTML=rows.filter(x=>String(x.kode_kantor)!=='000').map(x=>'<option value="'+esc(String(x.kode_kantor).padStart(3,'0'))+'">'+esc(String(x.kode_kantor).padStart(3,'0')+' - '+(x.nama_kantor||'Cabang'))+'</option>').join('')}
  async function load(){if(!branch()||state.loading)return;state.loading=true;try{const d=await post({type:'rbb_planning_data',tahun:year(),kode_kantor:branch(),kategori:CATEGORY});state.rows=d.rows||[];state.plan=d.plan||null;el('inputRbbDetailStatus').textContent=state.plan?.status||'Draft';render()}catch(e){el('inputRbbDetailBody').innerHTML='<tr><td colspan="16" class="mb-empty mb-negative">'+esc(e.message)+'</td></tr>'}finally{state.loading=false}}
  function collect(){return state.rows.map(r=>({kode_monbis:r.kode_monbis,values:Object.fromEntries([...document.querySelectorAll('.rbb-detail-input[data-code="'+CSS.escape(r.kode_monbis)+'"]')].map(i=>[i.dataset.month,Number(i.value||0)]))}))}
  async function save(){try{await post({type:'rbb_planning_save',tahun:year(),kode_kantor:branch(),rows:collect()});alert('Draft '+CATEGORY+' berhasil disimpan.');await load()}catch(e){alert(e.message)}}
  async function init(){document.querySelectorAll('[data-rbb-projection-category]').forEach(()=>{});document.getElementById('inputRbbDetailSave').addEventListener('click',save);['inputRbbDetailTahun','inputRbbDetailCabang'].forEach(id=>el(id).addEventListener('change',load));try{await offices();await load()}catch(e){el('inputRbbDetailBody').innerHTML='<tr><td colspan="16" class="mb-empty mb-negative">'+esc(e.message)+'</td></tr>'}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();
</script>
