<?php
// Report evaluasi cabang: closing bulanan, target RBB, dan capaian tahun berjalan.
?>

<div id="raportCabangPage">
  <section class="rc-header">
    <div class="rc-title-wrap">
      <div class="rc-title-icon" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19V5m0 14h16"/><path d="M8 15v-3m4 3V7m4 8V9m4 6V4"/></svg>
      </div>
      <div>
        <div class="rc-eyebrow">LAPORAN EVALUASI</div>
        <h1>Raport Cabang</h1>
        <p>Perbandingan closing bulanan terhadap RBB dan posisi akhir tahun.</p>
      </div>
    </div>
    <form class="rc-filters" onsubmit="event.preventDefault(); loadRaportCabang();">
      <label><span>Periode</span><input id="rcDate" type="date" onchange="loadRaportCabang()"></label>
      <label class="rc-office-field"><span>Kantor / Korwil</span><select id="rcOffice" onchange="loadRaportCabang()"><option value="000">Konsolidasi</option></select></label>
      <button id="rcExport" class="rc-export" type="button" onclick="exportRaportCabang()" disabled title="Ekspor report ke Excel">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12m0 0 5-5m-5 5-5-5M5 21h14"/></svg><span>Excel</span>
      </button>
    </form>
  </section>

  <section class="rc-report-card">
    <div class="rc-report-head">
      <div><h2 id="rcScopeTitle">Raport Kinerja</h2><p id="rcSubtitle">Pilih periode dan kantor untuk memuat data.</p></div>
      <div class="rc-report-meta"><span id="rcClosingBadge">Menunggu data</span><span id="rcStatus" role="status">Siap</span></div>
    </div>
    <div class="rc-note" id="rcNote">Nominal ditampilkan dalam Rupiah. Pendapatan, biaya, dan laba merupakan posisi kumulatif tahun berjalan.</div>
    <div class="rc-table-scroll" id="rcTableScroll" tabindex="0" aria-label="Tabel Raport Cabang, geser untuk melihat seluruh kolom">
      <table id="rcTable">
        <thead id="rcTableHead"></thead>
        <tbody id="rcTableBody"><tr><td class="rc-empty" colspan="19">Report dimuat otomatis setelah filter siap.</td></tr></tbody>
      </table>
    </div>
    <div class="rc-footnote"><span>Perubahan bulan berjalan = posisi bulan terakhir dikurangi closing Desember tahun sebelumnya; capaian tahunan = realisasi dikurangi target RBB. Capaian NPL memakai target dibagi realisasi, mengikuti formula Ikhtisar.</span><span id="rcSdmNote">Data SDM memakai roster pegawai aktif terkini.</span></div>
  </section>
</div>

<style>
  #raportCabangPage{--rc-ink:#18334d;--rc-muted:#74899d;--rc-line:#dbe5ec;--rc-teal:#087f8c;--rc-soft:#eff7f9;color:var(--rc-ink);font-family:Roboto,"Segoe UI",Arial,sans-serif;padding:12px;}
  .rc-header,.rc-report-card{border:1px solid var(--rc-line);border-radius:15px;background:#fff;box-shadow:0 5px 18px rgba(19,54,79,.055)}
  .rc-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 16px}
  .rc-title-wrap{display:flex;align-items:center;gap:12px;min-width:0}.rc-title-icon{display:grid;place-items:center;width:42px;height:42px;flex:0 0 auto;border-radius:12px;background:linear-gradient(145deg,#0b8797,#155e91);color:#fff}.rc-title-icon svg{width:22px;height:22px}.rc-eyebrow{margin-bottom:3px;color:#21849a;font-size:8px;font-weight:950;letter-spacing:.15em}.rc-title-wrap h1{margin:0;font-size:20px;line-height:1.2;font-weight:950;letter-spacing:-.025em}.rc-title-wrap p{margin:4px 0 0;color:var(--rc-muted);font-size:10px;font-weight:650}
  .rc-filters{display:flex;align-items:end;gap:8px;flex:0 0 auto}.rc-filters label{display:flex;flex-direction:column;gap:4px;min-width:145px}.rc-filters label span{padding-left:2px;color:#60768a;font-size:8px;font-weight:950;letter-spacing:.08em;text-transform:uppercase}.rc-filters input,.rc-filters select{height:36px;width:100%;border:1px solid #cddbe5;border-radius:9px;padding:0 10px;background:#fff;color:#193c58;font:800 10px Roboto,"Segoe UI",sans-serif;outline:0}.rc-filters input:focus,.rc-filters select:focus{border-color:#2588a0;box-shadow:0 0 0 3px rgba(37,136,160,.11)}.rc-export{display:flex;align-items:center;justify-content:center;gap:7px;height:36px;padding:0 12px;border:0;border-radius:9px;background:#07966b;color:#fff;font-size:10px;font-weight:900;cursor:pointer;box-shadow:0 5px 12px rgba(5,150,105,.16)}.rc-export:hover:not(:disabled){background:#047857;transform:translateY(-1px)}.rc-export:disabled{opacity:.5;cursor:not-allowed}.rc-export svg{width:17px;height:17px}
  .rc-report-card{margin-top:12px;overflow:hidden}.rc-report-head{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:13px 15px 10px}.rc-report-head h2{margin:0;font-size:13px;font-weight:950}.rc-report-head p{margin:4px 0 0;color:var(--rc-muted);font-size:9px;font-weight:650}.rc-report-meta{display:flex;align-items:center;gap:6px;flex-wrap:wrap;justify-content:flex-end}.rc-report-meta span{padding:5px 9px;border:1px solid #dce7ed;border-radius:999px;background:#f8fbfc;color:#547086;font-size:8px;font-weight:900;white-space:nowrap}.rc-report-meta #rcStatus[data-state="loading"]{background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.rc-report-meta #rcStatus[data-state="error"]{background:#fff1f2;color:#be123c;border-color:#fecdd3}.rc-report-meta #rcStatus[data-state="success"]{background:#ecfdf5;color:#047857;border-color:#bbf7d0}
  .rc-note{margin:0 15px 9px;color:#617c90;font-size:9px}.rc-table-scroll{max-height:min(72vh,860px);min-height:250px;overflow:auto;border-top:1px solid var(--rc-line);border-bottom:1px solid var(--rc-line);scrollbar-color:#afc1cc #f1f5f7;scrollbar-width:thin}.rc-table-scroll::-webkit-scrollbar{width:7px;height:7px}.rc-table-scroll::-webkit-scrollbar-thumb{border-radius:99px;background:#afc1cc}.rc-table-scroll::-webkit-scrollbar-track{background:#f1f5f7}
  #rcTable{width:100%;min-width:2060px;border-collapse:separate;border-spacing:0;table-layout:fixed;font-variant-numeric:tabular-nums}#rcTable th,#rcTable td{border-right:1px solid #d7e1e7;border-bottom:1px solid #d7e1e7}#rcTable thead{position:sticky;top:0;z-index:5}#rcTable thead th{height:30px;padding:5px 7px;background:#07858d;color:white;text-align:center;font-size:9px;line-height:1.15;font-weight:950;white-space:nowrap}#rcTable thead tr:nth-child(2) th{height:26px;background:#e7f3f5;color:#245a70;font-size:8px}#rcTable thead th:first-child{border-left:1px solid #d7e1e7}#rcTable .rc-col-label{width:230px}#rcTable .rc-col-baseline{width:125px}#rcTable .rc-col-year{width:125px}#rcTable .rc-col-month{width:104px}#rcTable .rc-col-summary{width:120px}#rcTable thead .rc-sticky-label{position:sticky;left:0;z-index:8}#rcTable tbody td{height:27px;padding:5px 8px;background:#fff;font-size:9px;line-height:1.15;white-space:nowrap}#rcTable tbody tr:nth-child(even):not(.rc-section) td{background:#fbfdfe}#rcTable tbody td:first-child{position:sticky;left:0;z-index:2;border-left:1px solid #d7e1e7;background:#fff;text-align:left;font-weight:780;box-shadow:5px 0 8px -8px rgba(18,48,71,.7)}#rcTable tbody tr:nth-child(even):not(.rc-section) td:first-child{background:#fbfdfe}#rcTable tbody td:not(:first-child){text-align:right}#rcTable tbody tr:hover:not(.rc-section) td{background:#f2f9fa}#rcTable tbody tr:hover:not(.rc-section) td:first-child{background:#f2f9fa}.rc-section td{position:static!important;height:25px!important;padding:6px 9px!important;background:#eaf4f6!important;color:#14566b;font-size:9px!important;font-weight:950!important;letter-spacing:.045em;text-transform:uppercase;text-align:left!important}.rc-value{font-family:Roboto,"Segoe UI",Arial,sans-serif;font-weight:750}.rc-empty{height:180px!important;text-align:center!important;color:#7d91a1!important;font-size:11px!important}.rc-current-month{background:#f0f8ff!important}.rc-delta-positive{color:#05815d}.rc-delta-negative{color:#d63a47}.rc-delta-neutral{color:#8495a4}.rc-current-month-head{background:#d9edf9!important;color:#164e73!important}.rc-footnote{display:flex;justify-content:space-between;gap:12px;padding:8px 14px;color:#74899d;font-size:8px;line-height:1.4}.rc-footnote span:last-child{text-align:right}
  @media(max-width:900px){#raportCabangPage{padding:8px}.rc-header{align-items:stretch;flex-direction:column}.rc-filters{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.4fr) auto}.rc-filters label{min-width:0}.rc-report-head{align-items:flex-start;flex-direction:column}.rc-report-meta{justify-content:flex-start}.rc-footnote{align-items:flex-start;flex-direction:column}.rc-footnote span:last-child{text-align:left}}
  @media(max-width:560px){.rc-title-wrap h1{font-size:18px}.rc-filters{grid-template-columns:1fr auto}.rc-office-field{grid-column:1/-1;grid-row:1}.rc-filters label:first-child{grid-column:1;grid-row:2}.rc-export{grid-column:2;grid-row:2}.rc-report-head{padding:11px}.rc-note{margin:0 11px 8px}}
</style>

<script>
const rcState = { data:null, rows:[], meta:null, employeeCount:null, abort:null, requestId:0 };
const rcMoneyFormat = new Intl.NumberFormat('id-ID',{maximumFractionDigits:0});
const rcRatioFormat = new Intl.NumberFormat('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2});
const rcKnownKorwil = new Set(['SEMARANG','SOLO','BANYUMAS','PEKALONGAN']);
function rcEscape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function rcNumber(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
function rcFormat(value,format){const n=rcNumber(value);if(n===null)return '–';if(format==='ratio')return rcRatioFormat.format(n)+'%';if(format==='count')return rcMoneyFormat.format(n);return rcMoneyFormat.format(n);}
function rcFormatDelta(value,format){const n=rcNumber(value);if(n===null)return '–';return (n>0?'+':'')+rcFormat(n,format);}
function rcAuthHeaders(extra={}){const headers=Object.assign({},extra);let token='';try{token=String(window.NavAuth?.getToken?.()||localStorage.getItem('dpk_token')||'').trim();}catch(e){}if(!token){try{const match=document.cookie.match(/(?:^|;\s*)sso_token=([^;]+)/);if(match)token=decodeURIComponent(match[1]);}catch(e){}}if(token)headers.Authorization=/^Bearer\s/i.test(token)?token:`Bearer ${token}`;return headers;}
function rcFetch(url,options={}){return fetch(url,Object.assign({},options,{headers:rcAuthHeaders(options.headers||{})}));}
function rcApiJson(response,label){return response.text().then(raw=>{let json;try{json=JSON.parse(raw)}catch(e){throw new Error(`${label}: respons server bukan JSON.`)}if(!response.ok||Number(json.status)>=400)throw new Error(json.message||`Gagal memuat ${label}`);return json;});}
function rcUserOffice(){const user=(window.getUser&&window.getUser())||{};const raw=user.kode||user.kode_kantor||user.kode_cabang||user.branch_code||'000';const code=String(raw).replace(/\D/g,'').padStart(3,'0').slice(-3);return code==='099'?'000':code;}
function rcSetStatus(text,state=''){const el=document.getElementById('rcStatus');el.textContent=text;el.dataset.state=state;}
async function rcLoadDate(){const input=document.getElementById('rcDate');try{const response=await rcFetch('./api/date/',{cache:'no-store'});const json=await rcApiJson(response,'Tanggal closing');const data=json.data||json;input.value=data.last_created||data.harian_date||new Date().toISOString().slice(0,10);}catch(e){input.value=new Date().toISOString().slice(0,10);}input.max=input.value;}
async function rcLoadOffices(){const select=document.getElementById('rcOffice');let html='<option value="000">Konsolidasi</option><optgroup label="Korwil">';for(const code of ['SEMARANG','SOLO','BANYUMAS','PEKALONGAN'])html+=`<option value="${code}">Korwil ${code[0]+code.slice(1).toLowerCase()}</option>`;html+='</optgroup><optgroup label="Cabang">';try{const response=await rcFetch('./api/kode/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'kode_kantor'})});const json=await rcApiJson(response,'Daftar kantor');(json.data||[]).filter(row=>row.kode_kantor&&row.kode_kantor!=='000').sort((a,b)=>String(a.kode_kantor).localeCompare(String(b.kode_kantor))).forEach(row=>{const code=String(row.kode_kantor).padStart(3,'0');html+=`<option value="${rcEscape(code)}">${rcEscape(code)} - ${rcEscape(row.nama_kantor||'')}</option>`;});}catch(e){}html+='</optgroup>';select.innerHTML=html;const userOffice=rcUserOffice();if(userOffice!=='000'&&[...select.options].some(option=>option.value===userOffice))select.value=userOffice;}
function rcScopePayload(date){const value=document.getElementById('rcOffice').value;const payload={type:'annual_report',harian_date:date};if(rcKnownKorwil.has(value))payload.korwil=value;else payload.kode_kantor=value;return payload;}
function rcAddSdmRows(data,employeeCount){const rows=[...(data.rows||[])];const meta=data.meta||{};const profit=rows.find(row=>row.key==='laba');const monthMeta=meta.months||[];const count=rcNumber(employeeCount);const headcountSeries=monthMeta.map(item=>item.available&&count!==null?count:null);const productivity=headcountSeries.map((headcount,index)=>{const laba=rcNumber(profit?.monthly?.[index]);if(!monthMeta[index]?.available||headcount===null||headcount<=0||laba===null)return null;return laba/headcount;});const latest=Number(meta.latest_actual_month||0);const sdm=[{section:'SDM',key:'sdm_count',label:'a. Jumlah SDM',format:'count',previous:null,monthly:headcountSeries,monthly_targets:Array(12).fill(null),year_target:null,current_actual:latest?headcountSeries[latest-1]:null,current_target:null,current_delta:null,current_achievement:null,year_actual:latest?headcountSeries[latest-1]:null,year_delta:null,year_achievement:null,comparison:false},{section:'SDM',key:'sdm_productivity',label:'b. Produktivitas SDM',format:'nominal',previous:null,monthly:productivity,monthly_targets:Array(12).fill(null),year_target:null,current_actual:latest?productivity[latest-1]:null,current_target:null,current_delta:null,current_achievement:null,year_actual:latest?productivity[latest-1]:null,year_delta:null,year_achievement:null,comparison:false}];const at=rows.findIndex(row=>row.section==='Rasio Keuangan');rows.splice(at<0?rows.length:at,0,...sdm);return rows;}
function rcHeaderHtml(meta){const months=(meta.months||[]);const current=Number(meta.latest_actual_month||0);return `<tr><th rowspan="2" class="rc-col-label rc-sticky-label">Indikator Kinerja</th><th rowspan="2" class="rc-col-baseline">Desember ${Number(meta.year)-1}</th><th rowspan="2" class="rc-col-year">RBB ${rcEscape(meta.year)}</th><th colspan="12">Realisasi ${rcEscape(meta.year)}</th><th colspan="2">Pencapaian RBB Bulan Berjalan${current?` · ${rcEscape(months[current-1]?.label||'')}`:''}</th><th colspan="2">Pencapaian RBB ${rcEscape(meta.year)}</th></tr><tr>${months.map((month,index)=>`<th class="rc-col-month${index+1===current?' rc-current-month-head':''}">${rcEscape(month.label)}</th>`).join('')}<th class="rc-col-summary">Target (+/-)</th><th class="rc-col-summary">%</th><th class="rc-col-summary">Target (+/-)</th><th class="rc-col-summary">%</th></tr>`;}
function rcDeltaClass(value,key){const n=rcNumber(value);if(n===null||Math.abs(n)<0.000001)return 'rc-delta-neutral';const inverse=key==='npl_gross'||key==='npl_netto';return (inverse?n<0:n>0)?'rc-delta-positive':'rc-delta-negative';}
function rcAchievementClass(value){const n=rcNumber(value);return n===null?'rc-delta-neutral':(n>=100?'rc-delta-positive':'rc-delta-negative');}
function rcRender(data,employeeCount){const meta=data.meta||{};const rows=rcAddSdmRows(data,employeeCount);rcState.data=data;rcState.rows=rows;rcState.meta=meta;document.getElementById('rcScopeTitle').textContent=`Raport Kinerja · ${meta.scope_label||'Kantor'}`;document.getElementById('rcSubtitle').textContent=`Posisi closing: ${meta.latest_actual_date||meta.harian_date||'—'} · Data sumber sistem keuangan, nominatif, dan RBB.`;document.getElementById('rcClosingBadge').textContent=meta.latest_actual_date?`Closing terakhir ${meta.latest_actual_date}`:'Closing belum tersedia';document.getElementById('rcTableHead').innerHTML=rcHeaderHtml(meta);const body=document.getElementById('rcTableBody');let html='',section='';const current=Number(meta.latest_actual_month||0);for(const row of rows){if(row.section!==section){section=row.section;html+=`<tr class="rc-section"><td colspan="19">${rcEscape(section)}</td></tr>`;}const monthly=(row.monthly||[]).map((value,index)=>`<td class="${index+1===current?'rc-current-month':''}">${rcEscape(rcFormat(value,row.format))}</td>`).join('');const valueCell=(value,format='nominal',extra='',signed=false)=>`<td class="${extra}">${rcEscape(signed?rcFormatDelta(value,format):rcFormat(value,format))}</td>`;html+=`<tr data-key="${rcEscape(row.key)}"><td title="${rcEscape(row.label)}">${rcEscape(row.label)}</td>${valueCell(row.previous,row.format)}${valueCell(row.year_target,row.format)}${monthly}${valueCell(row.current_delta,row.format,rcDeltaClass(row.current_delta,row.key),true)}${valueCell(row.current_achievement,'ratio',rcAchievementClass(row.current_achievement))}${valueCell(row.year_delta,row.format,rcDeltaClass(row.year_delta,row.key),true)}${valueCell(row.year_achievement,'ratio',rcAchievementClass(row.year_achievement))}</tr>`;}body.innerHTML=html||'<tr><td class="rc-empty" colspan="19">Belum ada data untuk filter ini.</td></tr>';document.getElementById('rcExport').disabled=!rows.length;document.getElementById('rcSdmNote').textContent=employeeCount===null?'SDM tidak tersedia; roster SIMPEG gagal dimuat.':'SDM adalah headcount roster aktif terkini (bukan histori bulanan).';}
async function loadRaportCabang(){const date=document.getElementById('rcDate').value;if(!date)return;const requestId=++rcState.requestId;if(rcState.abort)rcState.abort.abort();rcState.abort=new AbortController();rcSetStatus('Memuat…','loading');document.getElementById('rcExport').disabled=true;document.getElementById('rcTableBody').innerHTML='<tr><td class="rc-empty" colspan="19">Sedang mengambil data closing dan RBB…</td></tr>';try{const payload=rcScopePayload(date);const response=await rcFetch('./api/kinerja_report/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:rcState.abort.signal});const json=await rcApiJson(response,'Raport Cabang');const data=json.data||{};let employeeCount=null;try{const employeePayload={type:'rekap_anggota',as_of:data.meta?.latest_actual_date||date,summary_only:true};if(payload.korwil)employeePayload.korwil=payload.korwil;else employeePayload.kode_kantor=payload.kode_kantor;const employeeResponse=await rcFetch('./api/anggota/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(employeePayload),signal:rcState.abort.signal});const employeeJson=await rcApiJson(employeeResponse,'Rekap SDM');employeeCount=rcNumber(employeeJson.data?.meta?.total);}catch(e){if(e.name==='AbortError')throw e;}if(requestId!==rcState.requestId)return;rcRender(data,employeeCount);rcSetStatus('Data berhasil dimuat','success');}catch(error){if(error.name==='AbortError')return;rcSetStatus('Gagal memuat data','error');document.getElementById('rcTableBody').innerHTML=`<tr><td class="rc-empty" colspan="19">${rcEscape(error.message||'Terjadi kesalahan saat memuat report.')}</td></tr>`;}}
function rcExcelCell(value,format='nominal',signed=false){const n=rcNumber(value);if(n===null)return '<td></td>';const raw=String(n);const numberFormat=format==='ratio'?(signed?'+0.00"%";[Red]-0.00"%"':'0.00"%"'):(signed?'+#,##0.00;[Red]-#,##0.00':'#,##0.00;[Red]-#,##0.00');return `<td x:num="${raw}" style="mso-number-format:'${numberFormat}';text-align:right;">${raw}</td>`;}
function exportRaportCabang(){if(!rcState.rows.length||!rcState.meta)return;const meta=rcState.meta;const months=meta.months||[];const current=Number(meta.latest_actual_month||0);let html=`<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial,sans-serif;font-size:10pt}th,td{border:1px solid #7d8b91;padding:5px}th{background:#087f8c;color:#fff;font-weight:bold}.section{background:#eaf4f6;font-weight:bold;color:#14566b}.title{font-size:15pt;font-weight:bold;border:0}.sub{border:0}</style></head><body><table><tr><td class="title" colspan="19">RAPORT CABANG · ${rcEscape(meta.scope_label||'')}</td></tr><tr><td class="sub" colspan="19">Periode ${rcEscape(meta.harian_date||'')} · Closing terakhir ${rcEscape(meta.latest_actual_date||'—')} · Nominal Rupiah</td></tr><tr><th rowspan="2">Indikator Kinerja</th><th rowspan="2">Desember ${Number(meta.year)-1}</th><th rowspan="2">RBB ${rcEscape(meta.year)}</th><th colspan="12">Realisasi ${rcEscape(meta.year)}</th><th colspan="2">Pencapaian RBB Bulan Berjalan (${rcEscape(months[current-1]?.label||'—')})</th><th colspan="2">Pencapaian RBB ${rcEscape(meta.year)}</th></tr><tr>${months.map(month=>`<th>${rcEscape(month.label)}</th>`).join('')}<th>Target (+/-)</th><th>%</th><th>Target (+/-)</th><th>%</th></tr>`;let section='';for(const row of rcState.rows){if(row.section!==section){section=row.section;html+=`<tr class="section"><td colspan="19">${rcEscape(section)}</td></tr>`;}html+=`<tr><td>${rcEscape(row.label)}</td>${rcExcelCell(row.previous,row.format)}${rcExcelCell(row.year_target,row.format)}${(row.monthly||[]).map(value=>rcExcelCell(value,row.format)).join('')}${rcExcelCell(row.current_delta,row.format,true)}${rcExcelCell(row.current_achievement,'ratio')}${rcExcelCell(row.year_delta,row.format,true)}${rcExcelCell(row.year_achievement,'ratio')}</tr>`;}html+=`<tr><td colspan="19">SDM menggunakan roster pegawai aktif terkini; histori headcount per bulan tidak tersedia.</td></tr></table></body></html>`;const blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`Raport_Cabang_${String(document.getElementById('rcOffice').value).replace(/[^a-z0-9_-]/gi,'_')}_${document.getElementById('rcDate').value}.xls`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
(async()=>{await Promise.all([rcLoadDate(),rcLoadOffices()]);await loadRaportCabang();})();
</script>
