<?php
require_once __DIR__ . '/../components/bootstrap.php';
mb_ui_assets('.');

$potensiHead = mb_build_grouped_thead([
    ['label'=>'Kode','class'=>'mb-code-col mb-sticky-left','sort'=>'kode','attrs'=>['style'=>'width:44px']],
    ['label'=>'Kantor','class'=>'mb-sticky-left-2 mb-text-left','sort'=>'kantor','attrs'=>['id'=>'reportPotensiNameHead','style'=>'--mb-sticky-1:44px;width:136px']],
    ['label'=>'Total Potensi NPL','class'=>'mb-group mb-group--blue','sort'=>'total_baki'],
    ['label'=>'Aman / Lunas','class'=>'mb-group mb-group--green','sort'=>'baki_aman'],
    ['label'=>'Jatuh Tempo','class'=>'mb-group mb-group--amber','sort'=>'baki_jt'],
    ['label'=>'Flow (KL/D/M)','class'=>'mb-group mb-group--red','sort'=>'baki_flow'],
    ['label'=>'Masih Potensi','class'=>'mb-group mb-group--violet','sort'=>'baki_potensi'],
]);

mb_render_report_page([
    'id'=>'reportPotensiPage',
    'class'=>'mb-report-potensi',
    'header'=>[
        'id'=>'reportPotensiHeader',
        'title'=>'Potensi NPL',
        'subtitle'=>'Monitoring kandidat NPL, status penyelamatan, dan komitmen pembayaran.',
        'icon'=>mb_svg('warning'),
        'info_modal_id'=>'reportPotensiInfo',
        'filters'=>[
            ['id'=>'reportPotensiClosing','label'=>'Closing (M-1)','type'=>'date','width'=>'126px','attrs'=>['onclick'=>'this.showPicker && this.showPicker()']],
            ['id'=>'reportPotensiActual','label'=>'Actual (Harian)','type'=>'date','width'=>'126px','attrs'=>['onclick'=>'this.showPicker && this.showPicker()']],
            ['id'=>'reportPotensiArea','label'=>'Kantor','type'=>'select','width'=>'260px','options'=>['ALL'=>'Konsolidasi']],
        ],
        'actions'=>[],
    ],
    'toolbar'=>[
        'title'=>'Rekap Potensi NPL',
        'search'=>['id'=>'reportPotensiSearch','placeholder'=>'Cari kode / kantor...'],
        'actions'=>[
            ['attrs'=>['id'=>'reportPotensiExport'],'tone'=>'success','icon'=>'download','title'=>'Export Excel','aria_label'=>'Export Excel'],
        ],
    ],
    'table'=>[
        'wrapper_id'=>'reportPotensiTableWrap',
        'table_id'=>'reportPotensiTable',
        'loading_id'=>'reportPotensiLoading',
        'loading_text'=>'Memuat data potensi NPL...',
        'class'=>'mb-potensi-table mb-table--grouped-head',
        'colgroup_html'=>'<col style="width:44px"><col style="width:136px"><col style="width:116px"><col style="width:116px"><col style="width:116px"><col style="width:116px"><col style="width:116px">',
        'thead_html'=>$potensiHead,
        'tbody_ids'=>['reportPotensiTotal','reportPotensiBody'],
    ],
]);

mb_render_info_modal([
    'id'=>'reportPotensiInfo',
    'title'=>'Panduan Potensi NPL',
    'subtitle'=>'Kamus status dan cara membaca proyeksi NPL.',
    'body_html'=>'
      <div class="mb-npl-brief">
        <div class="mb-npl-brief__alert">
          <strong>Potensi NPL adalah rekening Lancar/DPK pada closing yang perlu dipantau sampai posisi actual.</strong>
          <span>Klik angka NOA untuk membuka rekening pembentuk setiap kelompok.</span>
        </div>
        <div class="mb-npl-brief__section">
          <div class="mb-npl-brief__section-title">Cara Membaca Potensi NPL</div>
          <div class="mb-npl-brief__priority-grid">
            <div class="mb-npl-brief__priority mb-npl-brief__priority--blue"><b>1</b><div><strong>Total Potensi</strong><span>Seluruh kandidat yang dipantau dari closing sampai actual.</span></div></div>
            <div class="mb-npl-brief__priority mb-npl-brief__priority--red"><b>2</b><div><strong>Flow dan Jatuh Tempo</strong><span>Prioritaskan rekening yang sudah masuk KL/D/M atau segera jatuh tempo.</span></div></div>
            <div class="mb-npl-brief__priority mb-npl-brief__priority--violet"><b>3</b><div><strong>Masih Potensi</strong><span>Lengkapi komitmen, tanggal janji, nominal, dan alasan untuk proyeksi penyelamatan.</span></div></div>
          </div>
        </div>
        <div class="mb-info-warning"><span>Catatan:</span><div>Aman/Lunas mencakup rekening yang tetap aman, membaik, backflow, atau sudah lunas sesuai hasil backend.</div></div>
      </div>'
]);

mb_render_detail_modal([
    'id'=>'reportPotensiDetail',
    'title'=>'Detail Potensi NPL',
    'subtitle'=>'Daftar rekening kandidat NPL',
    'size'=>'xl',
    'mobile_body_id'=>'reportPotensiDetailMobile',
    'search_near_close'=>true,
    'collapsible_filters'=>true,
    'toolbar_id'=>'reportPotensiDetailFilters',
    'search'=>['id'=>'reportPotensiDetailSearch','placeholder'=>'Cari detail...'],
    'filters'=>[
        ['id'=>'reportPotensiDetailStatus','label'=>'Status','type'=>'select','width'=>'145px','options'=>[
            'ALL'=>'Semua Status','AMAN'=>'Aman / Lunas','JATUH TEMPO'=>'Jatuh Tempo','FLOW KOLEK'=>'Flow Kolek','MASIH POTENSI'=>'Masih Potensi',
        ]],
        ['id'=>'reportPotensiDetailCommitment','label'=>'Komitmen','type'=>'select','width'=>'135px','options'=>[
            'ALL'=>'Semua Komitmen','SUDAH'=>'Sudah Komitmen','BELUM'=>'Belum Komitmen',
        ]],
        ['id'=>'reportPotensiDetailKankas','label'=>'Kankas','type'=>'select','width'=>'145px','options'=>[''=>'Semua Kankas']],
        ['id'=>'reportPotensiDetailAo','label'=>'AO','type'=>'select','width'=>'145px','options'=>[''=>'Semua AO']],
    ],
]);
?>

<script>
(() => {
  'use strict';
  const API_NPL='./api/npl/', API_DATE='./api/date/', API_KODE='./api/kode/';
  const ICON_EDIT=<?= json_encode(mb_svg('edit'), JSON_UNESCAPED_SLASHES) ?>,ICON_DOWNLOAD=<?= json_encode(mb_svg('download'), JSON_UNESCAPED_SLASHES) ?>;
  const KORWIL=[['SEMARANG','Korwil Semarang'],['SOLO','Korwil Solo'],['BANYUMAS','Korwil Banyumas'],['PEKALONGAN','Korwil Pekalongan']];
  const el=id=>document.getElementById(id), ui=()=>window.MonbisUI||{}, num=v=>Number(v||0);
  const esc=v=>ui().escape?ui().escape(v):String(v??'');
  const fmt=v=>ui().fmt?ui().fmt(v):new Intl.NumberFormat('id-ID').format(num(v));
  const fmtDate=value=>{if(!value)return '-';const d=new Date(String(value).length===10?value+'T00:00:00':value);return Number.isNaN(d.getTime())?'-':String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()};
  const state={rows:[],total:null,kantor:[],userKode:'000',sort:{column:'kode',direction:'asc'},abort:null,detail:[],detailKode:'000',detailKorwil:'',detailKankas:'',detailStatus:'ALL',detailPage:1,detailSize:20};

  async function post(url,body,signal){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{}),signal});const text=await response.text();let json={};try{json=text?JSON.parse(text):{}}catch(error){throw new Error('Response API bukan JSON')};if(!response.ok||Number(json.status)!==200)throw new Error(json.message||('HTTP '+response.status));return json}
  function currentUserKode(){const user=window.getUser?.()||{};const raw=user.kode_kantor||user.kode||user.kode_cabang||'000';const kode=String(raw).padStart(3,'0');return kode==='099'?'000':kode}
  function readDevUser(){if(window.getUser?.())return window.getUser();for(const key of ['dpk_user','app_user','user']){try{const user=JSON.parse(localStorage.getItem(key)||'null');if(user)return user}catch(error){}}return null}
  function canAccessDev(user){const fields=[user?.job_position,user?.unit_kerja,user?.branch_name,user?.role].map(value=>String(value||'').toLowerCase());return fields.some(value=>value.includes('divisi operasional'))||fields.includes('dev')}
  async function ensureDevAccess(){for(let attempt=0;attempt<15;attempt++){const user=readDevUser();if(user){if(canAccessDev(user))return true;el('reportPotensiPage').innerHTML='<section class="mb-report-card mb-dev-denied"><strong>Akses khusus Divisi Operasional</strong><span>Report Potensi NPL component masih berada di menu Dev Report.</span></section>';return false}await new Promise(resolve=>setTimeout(resolve,200))}return true}
  const rowCode=row=>String(row?.kode_cabang||row?.kode_unit||'').padStart(state.userKode==='000'?3:6,'0');
  const rowName=row=>row?.nama_cabang||row?.nama_kantor||'-';

  async function loadDates(){try{const response=await fetch(API_DATE);const json=await response.json();el('reportPotensiClosing').value=json.data?.last_closing||'';el('reportPotensiActual').value=json.data?.last_created||''}catch(error){const today=new Date().toISOString().slice(0,10);el('reportPotensiClosing').value=today;el('reportPotensiActual').value=today}}
  async function loadKantor(){try{const json=await post(API_KODE,{type:'kode_kantor'});state.kantor=Array.isArray(json.data)?json.data:[]}catch(error){state.kantor=[]}const select=el('reportPotensiArea');if(state.userKode!=='000'){const found=state.kantor.find(x=>String(x.kode_kantor).padStart(3,'0')===state.userKode);select.innerHTML='<option value="'+state.userKode+'">'+state.userKode+' - '+esc(found?.nama_kantor||'Cabang')+'</option>';select.disabled=true;return}let html='<option value="ALL">Konsolidasi</option>';KORWIL.forEach(item=>{html+='<option value="KOR-'+item[0]+'">'+item[1]+'</option>'});state.kantor.filter(x=>String(x.kode_kantor).padStart(3,'0')!=='000').sort((a,b)=>String(a.kode_kantor).localeCompare(String(b.kode_kantor),'id-ID',{numeric:true})).forEach(x=>{const kode=String(x.kode_kantor).padStart(3,'0');html+='<option value="'+kode+'">'+kode+' - '+esc(x.nama_kantor||'Cabang')+'</option>'});select.innerHTML=html}

  function sortValue(row,column){if(column==='kode')return rowCode(row);if(column==='kantor')return rowName(row);return row?.[column]}
  function visibleRows(){const query=String(el('reportPotensiSearch')?.value||'').trim().toLowerCase();const direction=state.sort.direction==='asc'?1:-1;return state.rows.filter(row=>!query||(rowCode(row)+' '+rowName(row)).toLowerCase().includes(query)).sort((a,b)=>{const av=sortValue(a,state.sort.column),bv=sortValue(b,state.sort.column);return ['kode','kantor'].includes(state.sort.column)?String(av||'').localeCompare(String(bv||''),'id-ID',{numeric:true})*direction:(num(av)-num(bv))*direction})}
  function updateSortIcons(){document.querySelectorAll('#reportPotensiTable .mb-sort').forEach(th=>{const icon=th.querySelector('.mb-sort-icon'),active=th.dataset.sort===state.sort.column;if(icon){icon.classList.toggle('is-active',active);icon.classList.toggle('is-desc',active&&state.sort.direction==='desc')}})}
  function bindSort(){document.querySelectorAll('#reportPotensiTable .mb-sort').forEach(th=>th.addEventListener('click',()=>{const column=th.dataset.sort;state.sort.direction=state.sort.column===column&&state.sort.direction==='asc'?'desc':'asc';state.sort.column=column;render()}));updateSortIcons()}
  function noaButton(value,status,kode,tone,korwil=''){const n=num(value);if(n<=0)return '<span class="mb-muted">0</span>';return '<button type="button" class="mb-potensi-noa mb-'+tone+'" data-status="'+esc(status)+'" data-kode="'+esc(kode)+'" data-korwil="'+esc(korwil)+'">'+fmt(n)+'</button>'}
  function potensiMetric(nominal,noa,status,kode,tone,korwil=''){const n=num(noa),content='<span class="mb-potensi-metric__value">'+(num(nominal)>0?fmt(nominal):'-')+'</span><span class="mb-subvalue">'+fmt(n)+' NOA</span>';return n>0?'<button type="button" class="mb-potensi-metric mb-potensi-metric--'+tone+'" data-status="'+esc(status)+'" data-kode="'+esc(kode)+'" data-korwil="'+esc(korwil)+'">'+content+'</button>':'<span class="mb-potensi-metric mb-potensi-metric--'+tone+'">'+content+'</span>'}
  function rowHtml(row,isTotal=false){const kode=isTotal?'ALL':rowCode(row),area=el('reportPotensiArea').value||'ALL',isKorwil=isTotal&&area.startsWith('KOR-'),detailKorwil=isKorwil?area.slice(4):'',detailKode=isTotal?(area==='ALL'||isKorwil?'000':area):kode,name=isTotal?'GRAND TOTAL':rowName(row);return '<tr class="'+(isTotal?'mb-total-row':'')+'"><td class="mb-code-col mb-sticky-left mb-code">'+kode+'</td><td class="mb-sticky-left-2 mb-name" style="--mb-sticky-1:44px" title="'+esc(name)+'">'+esc(name)+'<span class="mb-potensi-mobile-code">'+kode+'</span></td><td class="mb-num">'+potensiMetric(row.total_baki,row.total_noa,'ALL',detailKode,'blue',detailKorwil)+'</td><td class="mb-num">'+potensiMetric(row.baki_aman,row.noa_aman,'AMAN',detailKode,'green',detailKorwil)+'</td><td class="mb-num">'+potensiMetric(row.baki_jt,row.noa_jt,'JATUH TEMPO',detailKode,'amber',detailKorwil)+'</td><td class="mb-num">'+potensiMetric(row.baki_flow,row.noa_flow,'FLOW KOLEK',detailKode,'red',detailKorwil)+'</td><td class="mb-num">'+potensiMetric(row.baki_potensi,row.noa_potensi,'MASIH POTENSI',detailKode,'violet',detailKorwil)+'</td></tr>'}
  function render(){el('reportPotensiTotal').innerHTML=state.total?rowHtml(state.total,true):'';const rows=visibleRows();el('reportPotensiBody').innerHTML=rows.length?rows.map(row=>rowHtml(row)).join(''):'<tr><td colspan="7" class="mb-empty">Data tidak ditemukan.</td></tr>';updateSortIcons()}

  async function loadRekap(){if(state.abort)state.abort.abort();state.abort=new AbortController();ui().showLoading('reportPotensiLoading',true);try{const area=el('reportPotensiArea').value||'ALL',isKorwil=area.startsWith('KOR-');const json=await post(API_NPL,{type:'Potensi NPL',closing_date:el('reportPotensiClosing').value,harian_date:el('reportPotensiActual').value,kode_kantor:area==='ALL'||isKorwil?'':area,korwil:isKorwil?area.slice(4):''},state.abort.signal);state.rows=Array.isArray(json.data?.data)?json.data.data:[];state.total=json.data?.grand_total||null;el('reportPotensiNameHead').firstChild.textContent=area!=='ALL'&&!isKorwil?'Kankas ':'Kantor ';render();requestAnimationFrame(()=>{const wrap=el('reportPotensiTableWrap');if(wrap)wrap.scrollLeft=0});ui().closeMobileFilter('reportPotensiHeaderFilters')}catch(error){if(error.name!=='AbortError'){console.error(error);state.rows=[];state.total=null;el('reportPotensiTotal').innerHTML='';el('reportPotensiBody').innerHTML='<tr><td colspan="12" class="mb-empty mb-negative">Gagal memuat data potensi NPL.</td></tr>'}}finally{ui().showLoading('reportPotensiLoading',false)}}

  function normalizeStatus(row){const raw=String(row?.status_potensi||row?.status||'').trim().toUpperCase().replace(/[_-]+/g,' ');if(raw.includes('LUNAS')||raw.includes('AMAN')||raw.includes('BACKFLOW')||num(row?.baki_debet_harian)<=0)return 'AMAN';if(raw.includes('FLOW')||raw.includes('NPL'))return 'FLOW KOLEK';if(raw.includes('JATUH TEMPO')||raw==='JT')return 'JATUH TEMPO';return 'MASIH POTENSI'}
  function statusLabel(row){const kind=normalizeStatus(row);return kind==='AMAN'?'Aman / Lunas':kind==='FLOW KOLEK'?'Flow Kolek':kind==='JATUH TEMPO'?'Jatuh Tempo':'Masih Potensi'}
  function statusBadge(row){const kind=normalizeStatus(row),tone=kind==='AMAN'?'success':kind==='FLOW KOLEK'?'danger':kind==='JATUH TEMPO'?'amber':'neutral';return '<span class="mb-pill mb-pill--'+tone+'">'+statusLabel(row)+'</span>'}
  function commitment(row){return {text:row?.komitmen||row?.komitmen_dpd||'',date:row?.tgl_pembayaran||row?.tgl_janji_bayar||'',nominal:num(row?.nominal??row?.nominal_janji_bayar),reason:row?.alasan||row?.alasan_keterlambatan||''}}
  function hasCommitment(row){const c=commitment(row);return !!(String(c.text).trim()||String(c.date).trim()||c.nominal>0)}
  function filteredDetail(){const query=String(el('reportPotensiDetailSearch')?.value||'').trim().toLowerCase(),status=el('reportPotensiDetailStatus').value,commit=el('reportPotensiDetailCommitment').value;return state.detail.filter(row=>{const c=commitment(row),has=hasCommitment(row),haystack=(String(row.no_rekening||'')+' '+String(row.nama_nasabah||'')+' '+String(row.nama_ao||'')+' '+String(row.alamat||'')+' '+c.text+' '+c.reason).toLowerCase();return(status==='ALL'||normalizeStatus(row)===status)&&(commit==='ALL'||(commit==='SUDAH'?has:!has))&&(!query||haystack.includes(query))})}
  function detailSummary(rows){const safe=rows.filter(row=>normalizeStatus(row)==='AMAN').length,committed=rows.filter(hasCommitment).length,promise=rows.reduce((sum,row)=>sum+commitment(row).nominal,0);el('reportPotensiDetailSummary').classList.remove('is-hidden');el('reportPotensiDetailSummary').innerHTML='<div class="mb-summary-card mb-summary-card--blue"><div class="mb-summary-card__label">Data Terfilter</div><div class="mb-summary-card__value">'+fmt(rows.length)+'</div></div><div class="mb-summary-card mb-summary-card--green"><div class="mb-summary-card__label">Aman / Lunas</div><div class="mb-summary-card__value">'+fmt(safe)+'</div></div><div class="mb-summary-card mb-summary-card--amber"><div class="mb-summary-card__label">Sudah Komitmen</div><div class="mb-summary-card__value">'+fmt(committed)+'</div></div><div class="mb-summary-card"><div class="mb-summary-card__label">Nominal Janji</div><div class="mb-summary-card__value">Rp '+fmt(promise)+'</div></div>'}
  function renderDetailFooter(total,pages){const footer=el('reportPotensiDetailFooter');if(!total){footer.classList.add('is-hidden');footer.innerHTML='';return}footer.classList.remove('is-hidden');const from=(state.detailPage-1)*state.detailSize+1,to=Math.min(total,state.detailPage*state.detailSize);footer.innerHTML='<div class="mb-detail-page-info">Data '+fmt(from)+' - '+fmt(to)+' dari '+fmt(total)+'</div><div class="mb-detail-page-actions"><span class="mb-detail-footer-actions"><button type="button" class="mb-detail-footer-icon mb-detail-footer-icon--edit" id="reportPotensiDetailUpdate" title="Edit komitmen" aria-label="Edit komitmen">'+ICON_EDIT+'</button><button type="button" class="mb-detail-footer-icon mb-detail-footer-icon--export" id="reportPotensiDetailExport" title="Export detail" aria-label="Export detail">'+ICON_DOWNLOAD+'</button></span><span class="mb-detail-pagination"><button type="button" class="mb-detail-page-btn" id="reportPotensiPrev" '+(state.detailPage<=1?'disabled':'')+'>&lsaquo; Prev</button><span class="mb-detail-page-status">Hal '+state.detailPage+' / '+pages+'</span><button type="button" class="mb-detail-page-btn" id="reportPotensiNext" '+(state.detailPage>=pages?'disabled':'')+'>Next &rsaquo;</button></span></div>';el('reportPotensiDetailUpdate')?.addEventListener('click',gotoUpdate);el('reportPotensiDetailExport')?.addEventListener('click',()=>exportRows(filteredDetail(),true));el('reportPotensiPrev')?.addEventListener('click',()=>{state.detailPage--;renderDetail()});el('reportPotensiNext')?.addEventListener('click',()=>{state.detailPage++;renderDetail()})}
  function renderDetailMobile(rows){const mobile=el('reportPotensiDetailMobile');if(!mobile)return;if(!rows.length){mobile.innerHTML='<div class="mb-empty">Data tidak ditemukan pada filter ini.</div>';return}mobile.innerHTML=rows.map(row=>{const c=commitment(row),has=hasCommitment(row);return '<article class="mb-detail-card"><div class="mb-detail-card__head"><div class="mb-detail-card__identity"><div class="mb-detail-card__name">'+esc(row.nama_nasabah||'-')+'</div><div class="mb-detail-card__meta">'+esc(row.no_rekening||'-')+' · '+esc(row.nama_ao||'-')+'</div></div>'+statusBadge(row)+'</div><div class="mb-detail-card__metrics"><div class="mb-detail-card__metric"><span>BD Closing</span><strong>'+fmt(row.baki_debet_closing)+'</strong></div><div class="mb-detail-card__metric"><span>BD Actual</span><strong>'+fmt(row.baki_debet_harian)+'</strong></div><div class="mb-detail-card__metric"><span>Tunggakan P / B</span><strong>'+fmt(row.tunggakan_pokok)+' / '+fmt(row.tunggakan_bunga)+'</strong></div><div class="mb-detail-card__metric"><span>Saldo Tabungan</span><strong class="mb-positive">'+fmt(row.saldo_akhir)+'</strong></div><div class="mb-detail-card__metric"><span>Kolek Closing → Actual</span><strong>'+esc(row.kolek_closing||'-')+' → '+esc(row.kolek_harian||'-')+'</strong></div><div class="mb-detail-card__metric"><span>DPD / Pokok / Bunga</span><strong>'+fmt(row.hm_harian)+' / '+fmt(row.hmp_harian)+' / '+fmt(row.hmb_harian)+'</strong></div><div class="mb-detail-card__metric"><span>Jatuh Tempo</span><strong>'+fmtDate(row.jt_harian)+'</strong></div><div class="mb-detail-card__metric"><span>Angsuran P / B</span><strong>'+fmt(row.angsuran_pokok)+' / '+fmt(row.angsuran_bunga)+'</strong></div></div><div class="mb-detail-card__foot"><div class="mb-detail-card__note"><span>Status Komitmen</span><strong class="'+(has?'mb-positive':'mb-amber')+'">'+(has?'Sudah':'Belum')+'</strong></div><div class="mb-detail-card__note"><span>Nominal Janji</span><strong>'+fmt(c.nominal)+'</strong></div><div class="mb-detail-card__note"><span>Tanggal Janji</span><strong>'+fmtDate(c.date)+'</strong></div><div class="mb-detail-card__note"><span>Rencana / Alasan</span><strong title="'+esc((c.text||'-')+' · '+(c.reason||'-'))+'">'+esc(c.text||c.reason||'-')+'</strong></div></div></article>'}).join('')}
  function addDetailAddresses(rows){const mobile=el('reportPotensiDetailMobile');mobile?.querySelectorAll('.mb-detail-card').forEach((card,index)=>{const head=card.querySelector('.mb-detail-card__head');if(head&&!card.querySelector('.mb-detail-card__address'))head.insertAdjacentHTML('afterend','<div class="mb-detail-card__address"><span>Alamat</span><strong>'+esc(rows[index]?.alamat||'-')+'</strong></div>')});const desktopRows=Array.from(el('reportPotensiDetailBody')?.querySelectorAll('tbody tr')||[]).slice(1);desktopRows.forEach((tr,index)=>{const identity=tr.children[1];if(identity&&!identity.querySelector('.mb-detail-address'))identity.insertAdjacentHTML('beforeend','<span class="mb-subvalue mb-detail-address" title="'+esc(rows[index]?.alamat||'-')+'">'+esc(rows[index]?.alamat||'-')+'</span>')})}
  function syncDetailMobile(){const all=filteredDetail(),pages=Math.max(1,Math.ceil(all.length/state.detailSize));state.detailPage=Math.min(Math.max(1,state.detailPage),pages);const rows=all.slice((state.detailPage-1)*state.detailSize,state.detailPage*state.detailSize);renderDetailMobile(rows);addDetailAddresses(rows)}
  function renderDetail(){const all=filteredDetail(),pages=Math.max(1,Math.ceil(all.length/state.detailSize));state.detailPage=Math.min(Math.max(1,state.detailPage),pages);const rows=all.slice((state.detailPage-1)*state.detailSize,state.detailPage*state.detailSize);detailSummary(all);const totals=all.reduce((sum,row)=>{sum.closing+=num(row.baki_debet_closing);sum.actual+=num(row.baki_debet_harian);sum.promise+=commitment(row).nominal;return sum},{closing:0,actual:0,promise:0});const bodyRows=rows.map(row=>{const c=commitment(row);return '<tr><td class="mb-sticky-left mb-code" style="width:120px">'+esc(row.no_rekening||'-')+'</td><td class="mb-sticky-left-2 mb-name" style="--mb-sticky-1:120px;width:170px" title="'+esc(row.nama_nasabah||'-')+'">'+esc(row.nama_nasabah||'-')+'<span class="mb-subvalue">'+esc(row.nama_ao||'-')+'</span></td><td class="mb-text-center">'+statusBadge(row)+'</td><td class="mb-text-center">'+esc(row.kolek_closing||'-')+' → '+esc(row.kolek_harian||'-')+'</td><td class="mb-num">'+fmt(row.baki_debet_closing)+'</td><td class="mb-num">'+fmt(row.baki_debet_harian)+'</td><td class="mb-num">'+fmt(row.tunggakan_pokok)+'<span class="mb-subvalue">B: '+fmt(row.tunggakan_bunga)+'</span></td><td class="mb-num mb-positive">'+fmt(row.saldo_akhir)+'</td><td class="mb-text-center">'+fmtDate(row.jt_harian)+'</td><td class="mb-text-center">'+fmt(row.hm_harian)+'<span class="mb-subvalue">P '+fmt(row.hmp_harian)+' · B '+fmt(row.hmb_harian)+'</span></td><td class="mb-num">'+fmt(row.angsuran_pokok)+'<span class="mb-subvalue">B: '+fmt(row.angsuran_bunga)+'</span></td><td class="mb-text-center"><span class="mb-pill '+(hasCommitment(row)?'mb-pill--success':'mb-pill--amber')+'">'+(hasCommitment(row)?'Sudah':'Belum')+'</span></td><td title="'+esc(c.text)+'">'+esc(c.text||'-')+'</td><td class="mb-text-center">'+fmtDate(c.date)+'</td><td class="mb-num">'+fmt(c.nominal)+'</td><td title="'+esc(c.reason)+'">'+esc(c.reason||'-')+'</td></tr>'}).join('');el('reportPotensiDetailBody').innerHTML='<table class="mb-table mb-detail-mini mb-potensi-detail-table"><thead><tr><th class="mb-sticky-left" style="width:120px">Rekening</th><th class="mb-sticky-left-2 mb-text-left" style="--mb-sticky-1:120px;width:170px">Nasabah / AO</th><th>Status</th><th>Kolek C → H</th><th>BD Closing</th><th>BD Actual</th><th>Tunggakan P / B</th><th>Saldo Tab</th><th>JT</th><th>DPD / P / B</th><th>Angsuran P / B</th><th>Komitmen</th><th>Rencana</th><th>Tgl Janji</th><th>Nominal Janji</th><th>Alasan</th></tr></thead><tbody><tr class="mb-total-row"><td class="mb-sticky-left" style="width:120px">TOTAL</td><td class="mb-sticky-left-2" style="--mb-sticky-1:120px;width:170px">'+fmt(all.length)+' Debitur</td><td colspan="2"></td><td class="mb-num">'+fmt(totals.closing)+'</td><td class="mb-num">'+fmt(totals.actual)+'</td><td colspan="8"></td><td class="mb-num">'+fmt(totals.promise)+'</td><td></td></tr>'+bodyRows+'</tbody></table>';renderDetailFooter(all.length,pages)}

  function toggleDetailOfficeFilters(show){['reportPotensiDetailKankas','reportPotensiDetailAo'].forEach(id=>el(id)?.closest('.mb-field')?.classList.toggle('is-hidden',!show))}
  async function loadDetailOptions(){const show=state.detailKode!=='000';toggleDetailOfficeFilters(show);if(!show)return;const [kankas,ao]=await Promise.all([post(API_KODE,{type:'kode_kankas',kode_kantor:state.detailKode}).catch(()=>({data:[]})),post(API_KODE,{type:'kode_ao_kredit',kode_kantor:state.detailKode}).catch(()=>({data:[]}))]);el('reportPotensiDetailKankas').innerHTML='<option value="">Semua Kankas</option>'+((kankas.data||[]).map(x=>'<option value="'+esc(x.kode_group1)+'">'+esc(x.kode_group1)+' - '+esc(x.deskripsi_group1||'Kankas')+'</option>').join(''));el('reportPotensiDetailAo').innerHTML='<option value="">Semua AO</option>'+((ao.data||[]).map(x=>'<option value="'+esc(x.kode_group2)+'">'+esc(x.nama_ao||x.kode_group2)+'</option>').join(''));el('reportPotensiDetailKankas').value=state.detailKankas}
  async function fetchDetail(){el('reportPotensiDetailBody').innerHTML='<div class="mb-empty">Memuat detail debitur...</div>';try{const json=await post(API_NPL,{type:'Debitur Potensi NPL',kode_kantor:state.detailKode==='000'?'':state.detailKode,korwil:state.detailKorwil,kode_kankas:el('reportPotensiDetailKankas')?.value||state.detailKankas,kode_ao:el('reportPotensiDetailAo')?.value||'',closing_date:el('reportPotensiClosing').value,harian_date:el('reportPotensiActual').value,status_filter:'ALL',include_lunas:1,include_aman_backflow:1});state.detail=Array.isArray(json.data)?json.data:[];state.detailPage=1;renderDetail()}catch(error){console.error(error);state.detail=[];el('reportPotensiDetailBody').innerHTML='<div class="mb-empty mb-negative">Gagal memuat detail potensi NPL.</div>';renderDetailFooter(0,1)}}
  async function openDetail(kode,status,korwil=''){const clean=String(kode||'000'),isKankas=clean.length>3;state.detailKode=clean==='ALL'?'000':(isKankas?clean.slice(0,3):clean);state.detailKorwil=String(korwil||'');state.detailKankas=isKankas?clean:'';state.detailStatus=status||'ALL';el('reportPotensiDetailStatus').value=state.detailStatus;el('reportPotensiDetailCommitment').value='ALL';el('reportPotensiDetailSearch').value='';const scope=state.detailKorwil?'Korwil '+state.detailKorwil:(clean==='000'?'Konsolidasi':clean);el('reportPotensiDetailTitle').textContent='Detail Potensi NPL - '+scope;el('reportPotensiDetailSubtitle').textContent='Posisi '+fmtDate(el('reportPotensiClosing').value)+' vs '+fmtDate(el('reportPotensiActual').value);ui().closeMobileFilter('reportPotensiDetailFilters');ui().openModal('reportPotensiDetail');await loadDetailOptions();fetchDetail()}

  function exportRows(rows,detail=false){if(!rows.length)return;let html;if(detail){html='<table border="1"><thead><tr><th>Rekening</th><th>Nasabah</th><th>AO</th><th>Status</th><th>Kolek Closing</th><th>BD Closing</th><th>Kolek Actual</th><th>BD Actual</th><th>Tunggakan Pokok</th><th>Tunggakan Bunga</th><th>Saldo Tabungan</th><th>Jatuh Tempo</th><th>DPD</th><th>DPD Pokok</th><th>DPD Bunga</th><th>Angsuran Pokok</th><th>Angsuran Bunga</th><th>Komitmen</th><th>Tgl Janji</th><th>Nominal Janji</th><th>Alasan</th></tr></thead><tbody>'+rows.map(row=>{const c=commitment(row);return '<tr><td style="mso-number-format:\'\\@\'">'+esc(row.no_rekening||'')+'</td><td>'+esc(row.nama_nasabah||'')+'</td><td>'+esc(row.nama_ao||'')+'</td><td>'+statusLabel(row)+'</td><td>'+esc(row.kolek_closing||'')+'</td><td>'+num(row.baki_debet_closing)+'</td><td>'+esc(row.kolek_harian||'')+'</td><td>'+num(row.baki_debet_harian)+'</td><td>'+num(row.tunggakan_pokok)+'</td><td>'+num(row.tunggakan_bunga)+'</td><td>'+num(row.saldo_akhir)+'</td><td>'+esc(row.jt_harian||'')+'</td><td>'+num(row.hm_harian)+'</td><td>'+num(row.hmp_harian)+'</td><td>'+num(row.hmb_harian)+'</td><td>'+num(row.angsuran_pokok)+'</td><td>'+num(row.angsuran_bunga)+'</td><td>'+esc(c.text)+'</td><td>'+esc(c.date)+'</td><td>'+c.nominal+'</td><td>'+esc(c.reason)+'</td></tr>'}).join('')+'</tbody></table>'}else{const all=state.total?[{...state.total,kode_cabang:'ALL',nama_cabang:'GRAND TOTAL'},...rows]:rows;html='<table border="1"><thead><tr><th>Kode</th><th>Kantor</th><th>Total NOA</th><th>Total Baki</th><th>NOA Aman</th><th>Baki Aman</th><th>NOA JT</th><th>Baki JT</th><th>NOA Flow</th><th>Baki Flow</th><th>NOA Potensi</th><th>Baki Potensi</th></tr></thead><tbody>'+all.map(row=>'<tr><td>'+esc(row.kode_cabang||'')+'</td><td>'+esc(row.nama_cabang||'')+'</td><td>'+num(row.total_noa)+'</td><td>'+num(row.total_baki)+'</td><td>'+num(row.noa_aman)+'</td><td>'+num(row.baki_aman)+'</td><td>'+num(row.noa_jt)+'</td><td>'+num(row.baki_jt)+'</td><td>'+num(row.noa_flow)+'</td><td>'+num(row.baki_flow)+'</td><td>'+num(row.noa_potensi)+'</td><td>'+num(row.baki_potensi)+'</td></tr>').join('')+'</tbody></table>'}const blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(detail?'Detail_':'')+'Potensi_NPL_'+(el('reportPotensiActual').value||'data')+'.xls';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function gotoUpdate(){sessionStorage.setItem('flowpar_update',JSON.stringify({source:'potensi_npl',kode_kantor:state.detailKode==='000'?'':state.detailKode,korwil:state.detailKorwil,kode_kankas:el('reportPotensiDetailKankas')?.value||'',kode_ao:el('reportPotensiDetailAo')?.value||'',status_filter:el('reportPotensiDetailStatus').value,commitment_filter:el('reportPotensiDetailCommitment').value,closing_date:el('reportPotensiClosing').value,harian_date:el('reportPotensiActual').value}));sessionStorage.removeItem('potensinpl_update');window.location.href='./update_flowpar'}

  async function init(){if(!(await ensureDevAccess()))return;state.userKode=currentUserKode();await Promise.all([loadDates(),loadKantor()]);['reportPotensiClosing','reportPotensiActual','reportPotensiArea'].forEach(id=>el(id)?.addEventListener('change',loadRekap));el('reportPotensiSearch')?.addEventListener('input',ui().debounce?ui().debounce(render,160):render);el('reportPotensiExport')?.addEventListener('click',()=>exportRows(visibleRows()));el('reportPotensiTable')?.addEventListener('click',event=>{const button=event.target.closest('[data-status][data-kode]');if(button)openDetail(button.dataset.kode,button.dataset.status,button.dataset.korwil)});['reportPotensiDetailSearch','reportPotensiDetailStatus','reportPotensiDetailCommitment'].forEach(id=>el(id)?.addEventListener(id.includes('Search')?'input':'change',()=>{state.detailPage=1;renderDetail()}));['reportPotensiDetailKankas','reportPotensiDetailAo'].forEach(id=>el(id)?.addEventListener('change',fetchDetail));bindSort();loadRekap()}
  const boot=()=>{const desktop=el('reportPotensiDetailBody');if(desktop)new MutationObserver(syncDetailMobile).observe(desktop,{childList:true});init()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
</script>
